name: CD

on:
  push:
    branches: [ main ]   # deploy only from main 


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ------------------------
      # Checkout repo
      # ------------------------
      - name: Checkout repository
        uses: actions/checkout@v4

      # ------------------------
      # Python setup
      # ------------------------
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # ------------------------
      # Install dbt
      # ------------------------
      - name: Install dbt Snowflake adapter
        run: |
          python -m pip install --upgrade pip
          pip install dbt-snowflake

      # ------------------------
      # Configure dbt profile
      # ------------------------
      - name: Setup dbt profile
        run: |
          mmkdir -p ~/.dbt
          cat > ~/.dbt/profiles.yml << 'EOL'
          banking_dbt:
            target: prod
            outputs:
              prod:
                type: snowflake
                account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
                user: "{{ env_var('SNOWFLAKE_USER') }}"
                password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
                role: ACCOUNTADMIN
                database: CORE_BANKING_DB
                warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
                schema: STAGING
          EOL

      # ------------------------
      # Deploy dbt project
      # ------------------------
      - name: dbt run + test (prod)
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
        run: |
          cd banking_dbt
          dbt deps
          dbt run    # builds production models on Snowflake
          dbt test   # validates production data